version: '3'

services:
    pfa-mysql:
        image: mysql:5.7
        # container_name: pfa-mysql
        # build: ./mysql
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - app-mysql-net

    app:
        container_name: pfa-app
        build: ./app/fpa-spring-rest-service
        depends_on:
            - pfa-mysql
        networks: 
            - app-mysql-net
            - app-nginx-net

    nginx:
        container_name: pfa-nginx
        build: nginx
        ports:
            - 8000:80
        depends_on: 
            - app
        networks: 
            - app-nginx-net

networks:
    app-nginx-net:
        driver: bridge
    app-mysql-net:
        driver: bridge
    